FROM node:22.17.0-alpine AS deps
RUN corepack enable pnpm
WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/bot/package.json ./apps/bot/
RUN pnpm install --frozen-lockfile

FROM node:22.17.0-alpine
RUN corepack enable pnpm
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/apps/bot/node_modules ./apps/bot/node_modules
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/bot ./apps/bot
WORKDIR /app/apps/bot
ENV ENVIRONMENT=prod
CMD ["pnpm", "start"]
