name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Bot Docker Build
        run: pnpm --filter @shorty/bot docker:build
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js and PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.13.1
      - uses: actions/setup-node@v4
        with:
          node-version: 22.17.0
          cache: "pnpm"

      - name: Install Deps
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

      - name: Unit Tests
        run: pnpm run test
