name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install modules
        run: pnpm install
      - name: Run tests
        run: pnpm run test
